name: viniloteca
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  # Ojo con la indentación aquí, asegúrate de que 'sdk'
  # esté dos espacios por delante de 'environment'
  sdk: '>=3.9.0 <4.0.0' # Es mejor especificar un rango

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  image_picker: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# Esta es la sección principal de configuración de Flutter
flutter:
  uses-material-design: true

  # AQUÍ es donde van los assets
  assets:
    - assets/